# Use the official MySQL 8.0 image as the base
FROM mysql:8.0

# Copy the SQL script into the container at the specified location
COPY ./mysql.sql /docker-entrypoint-initdb.d/

# The MySQL container automatically runs the scripts in /docker-entrypoint-initdb.d/ on container start.
# So you don't need to specify `--init-file` explicitly.

# Expose the default MySQL port
EXPOSE 3306
