apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: database-container
        image: 318623136204.dkr.ecr.us-east-1.amazonaws.com/docker-containers:mysql-app_latest
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        envFrom:
          - secretRef:
              name: db-secrets
        ports:
        - containerPort: 3306
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
