apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
        - name: flask-app
          image: 318623136204.dkr.ecr.us-east-1.amazonaws.com/docker-containers:flask-app_latest
          imagePullPolicy: Always
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_USER
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: clo835
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: clo835
                  key: DBPORT
            - name: GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  name: clo835
                  key: GROUP_NAME
            - name: BACKGROUND_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: clo835
                  key: BACKGROUND_IMAGE
            - name: APP_COLOR
              valueFrom:
                configMapKeyRef:
                  name: clo835
                  key: APP_COLOR
          ports:
            - containerPort: 81
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.5"
