apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: final
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # "password" in base64
  MYSQL_DATABASE: ZW1wbG95ZWVz      # "employees" in base64
