apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: final
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # "password" in base64
  DBUSER: cm9vdA==              # "root" in base64
